from pydantic import BaseModel, ConfigDict
from datetime import datetime
from typing import Optional, List, Dict
from pydantic import Field # Added for explicit field definition if needed


class UserBase(BaseModel):
    # Use a plain string here because the default admin uses a .local domain
    # which is not considered a valid RFC-compliant email by EmailStr.
    username: Optional[str] = Field(None, max_length=100)
    email: str

class UserCreate(UserBase):
    password: str
    invitation_token: Optional[str] = None

class UserRead(UserBase):
    id: int
    is_admin: bool

    model_config = ConfigDict(from_attributes=True)


class RegisterResponse(BaseModel):
    user: UserRead
    organization_id: int
    organization_name: str
    access_token: str
    token_type: str = "bearer"
    workspace_created: bool = False


class WaitlistCreate(BaseModel):
    email: str
    source: Optional[str] = None


class WaitlistResponse(BaseModel):
    email: str
    already_exists: bool = False

class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"

class TokenData(BaseModel):
    email: Optional[str] = None


class BootstrapStatus(BaseModel):
    needs_admin: bool


class SSOProviderInfo(BaseModel):
    name: str
    enabled: bool


class SSOStatus(BaseModel):
    enabled: bool
    provider_name: Optional[str] = None
    providers: list[SSOProviderInfo] = []


class BootstrapAdminCreate(BaseModel):
    username: str
    password: str
    email: Optional[str] = None


class DetectionBase(BaseModel):
    technique_id: str = Field(..., max_length=50)
    title: str = Field(..., max_length=500)
    description: Optional[str] = Field(None, max_length=10000)
    sigma_rule: Optional[str] = Field(None, max_length=50000)
    siem_type: str = Field(..., max_length=50)
    siem_query: str = Field(..., max_length=10000)
    scheduled: Optional[bool] = False # for future

    # Fields for last test status and score
    last_result: Optional[str] = None
    last_score: Optional[int] = None
    last_tested_at: Optional[datetime] = None
    last_pass_at: Optional[datetime] = None
    last_fail_at: Optional[datetime] = None
    last_alert_at: Optional[datetime] = None
    status: Optional[str] = None
    last_reviewed_at: Optional[datetime] = None
    owner: Optional[str] = None
    notes: Optional[str] = None


class DetectionCreate(DetectionBase):
    # No id here, DB generates it
    pass


class DetectionUpdate(BaseModel):
    """Schema for partial detection updates (PATCH)."""
    owner: Optional[str] = Field(None, max_length=255, description="Email of the detection owner")
    notes: Optional[str] = Field(None, max_length=10000, description="Review notes")
    status: Optional[str] = Field(None, max_length=50, description="Lifecycle status")
    criticality: Optional[str] = Field(None, max_length=20, description="Criticality level")


class Detection(DetectionBase):
    id: str
    created_at: Optional[datetime] = None
    last_updated_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)

class TestBase(BaseModel):
    # detection_id can be null for scenario / telemetry-only runs,
    # so keep this optional to match the database shape.
    detection_id: Optional[str] = Field(None, max_length=50)
    technique_id: str = Field(..., max_length=50)
    marker: Optional[str] = Field(None, max_length=100) # Marker can be generated by backend
    environment: str = Field("lab", max_length=20)  # "lab" | "prod"
    endpoint: Optional[str] = Field(None, max_length=255)
    initiated_by_user_id: Optional[int] = None
    initiated_by_email: Optional[str] = Field(None, max_length=255)
    initiated_by_username: Optional[str] = Field(None, max_length=100)
    initiated_by_role: Optional[str] = Field(None, max_length=100)
    status: str = Field("pending", max_length=50)
    result: Optional[str] = Field(None, max_length=1000)
    score: Optional[int] = None
    # summary: Optional[str] = None # Removed as per new model
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None

class TestCreate(TestBase):
    pass

class Test(TestBase):
    id: int
    started_at: datetime # Re-added
    status: str # Re-added

    model_config = ConfigDict(from_attributes=True)

class TestRunCreate(BaseModel):
    # Optional detection that this run is tied to. When omitted, the test is
    # treated as a scenario/telemetry run driven by technique_id only.
    detection_id: Optional[str] = None
    # Optional technique identifier for scenario‑driven runs (e.g. from Explore).
    technique_id: Optional[str] = None
    environment: str = "lab"
    endpoint: Optional[str] = None
    # Optional hint from the UI about how this run should be interpreted.
    # For now this is primarily used for orchestration / reporting and may be
    # DETECTION_VALIDATION, ALERT_CHECK or TELEMETRY_CHECK.
    mode: Optional[str] = "DETECTION_VALIDATION"

# Removed TestRunRequest as it is replaced by TestRunCreate

class TestArtifactBase(BaseModel):
    test_id: int # Re-added
    atomic_command: Optional[str] = None
    siem_sample_events: Optional[str] = None
    # event_count: Optional[int] = None # Removed as per new model
    ai_explanation: Optional[str] = None
    ai_suggested_rule: Optional[str] = None
    ai_root_cause_category: Optional[str] = "OTHER"
    ai_confidence_score: Optional[int] = 0

class TestArtifactCreate(TestArtifactBase):
    pass

class TestArtifact(TestArtifactBase):
    id: int

    model_config = ConfigDict(from_attributes=True)


class TestWithDetectionTitle(Test):
    detection_title: str

class TestDetailResponse(Test):
    detection: Optional[Detection] = None
    artifact: Optional[TestArtifact] = None # No longer a forward reference


class DetectionSignalPayload(BaseModel):
    """Payload shape for a single qualifying detection/alert used in scoring."""

    detection_time: datetime
    is_qualifying: bool = True

    specificity_level: Optional[str] = None
    detection_type: Optional[str] = None
    uses_process_tree: bool = False
    uses_multi_condition: bool = False
    expected_fp_rate: Optional[str] = None
    severity: Optional[str] = None

    # 5W enrichment fields
    user_name: Optional[str] = None
    user_domain: Optional[str] = None
    user_email: Optional[str] = None
    user_id: Optional[str] = None
    user_sid: Optional[str] = None

    host_name: Optional[str] = None
    host_fqdn: Optional[str] = None
    asset_id: Optional[str] = None
    device_id: Optional[str] = None
    asset_criticality: Optional[str] = None
    os_type: Optional[str] = None
    os_version: Optional[str] = None

    process_name: Optional[str] = None
    process_command_line: Optional[str] = None
    parent_process_name: Optional[str] = None
    parent_process_id: Optional[str] = None
    event_type: Optional[str] = None

    event_time: Optional[datetime] = None
    log_time: Optional[datetime] = None

    src_ip: Optional[str] = None
    src_port: Optional[int] = None
    src_geo: Optional[str] = None
    src_hostname: Optional[str] = None
    src_asn: Optional[str] = None

    dest_ip: Optional[str] = None
    dest_domain: Optional[str] = None
    dest_port: Optional[int] = None
    dest_hostname: Optional[str] = None
    dest_geo: Optional[str] = None
    url: Optional[str] = None

    technique_id: Optional[str] = None
    tactic: Optional[str] = None
    framework: Optional[str] = None
    rule_name: Optional[str] = None
    detection_rule_id: Optional[str] = None
    category: Optional[str] = None

    log_source: Optional[str] = None
    vendor: Optional[str] = None
    env_size_bucket: Optional[str] = None


class ScoreTestRunRequest(BaseModel):
    """Request body for computing a C/T/F/E + 5W score for a test run."""

    attack_start_time: datetime
    detections: List[DetectionSignalPayload]


class ScoreTestRunResponse(BaseModel):
    coverage: int
    timeliness: int
    fidelity: float
    enrichment: int
    enrichment_breakdown: Dict[str, int]
    base_score: float
    ml_adjustment: float
    final_score: float
    delay_seconds: Optional[float]


class AtomicArgSpec(BaseModel):
    name: str
    label: str
    type: Optional[str] = "string"
    required: Optional[bool] = True
    default: Optional[str] = None
    description: Optional[str] = None
    options: Optional[List[str]] = None


class AtomicTestDefinition(BaseModel):
    id: str
    technique_id: str
    name: str
    description: Optional[str] = None
    source: str = "atomic-red-team"
    platforms: List[str] = []
    is_safe: Optional[bool] = True
    args: List[AtomicArgSpec] = []


class MitreTechnique(BaseModel):
    id: str
    name: str
    tactics: List[str]  # Human-readable tactic names, e.g. "Execution"
    is_subtechnique: bool = False

class DetectionAlert(BaseModel):
    id: int
    name: str
    time: datetime
    severity: str
    host: Optional[str] = None
    query: str
    raw_event: str
    # Optional link back to the PurveX test this alert was associated with,
    # when it was generated by a validation run rather than a live incident.
    test_id: Optional[int] = None


class ReportBase(BaseModel):
    start_date: datetime
    end_date: datetime
    environments: List[str]  # ["lab", "dev", "prod"]


class ReportCreate(ReportBase):
    title: Optional[str] = None


class Report(ReportBase):
    id: int
    report_id: str
    organization_id: int
    generated_by: int
    generated_at: datetime
    title: str
    overall_health_score: Optional[int] = None
    total_detections: int
    total_tests: int
    file_path: Optional[str] = None
    file_size: Optional[int] = None

    model_config = ConfigDict(from_attributes=True)


class OrganizationBase(BaseModel):
    name: str
    primary_contact_email: Optional[str] = None
    timezone: str = "UTC"
    locale: str = "en_US"
    default_environment_names: str = '["lab", "dev", "prod"]'
    compliance_mode_flags: str = '[]'

class OrganizationCreate(OrganizationBase):
    pass

class Organization(OrganizationBase):
    id: int

    model_config = ConfigDict(from_attributes=True)


class OrganizationSSOSettingsBase(BaseModel):
    enabled: bool = False
    provider_type: str = "oidc"
    provider_name: Optional[str] = None
    issuer_url: Optional[str] = None
    client_id: Optional[str] = None
    client_secret: Optional[str] = None
    scopes: str = "openid profile email"
    allowed_email_domains: List[str] = []
    enforce_sso: bool = False
    allow_password_login: bool = True
    jit_provisioning_enabled: bool = False
    default_role_id: Optional[int] = None


class OrganizationSSOSettingsCreate(OrganizationSSOSettingsBase):
    pass


class OrganizationSSOSettings(OrganizationSSOSettingsBase):
    id: int
    organization_id: int
    client_secret_configured: bool = False

    model_config = ConfigDict(from_attributes=True)

class SIEMConnectionBase(BaseModel):
    siem_type: str
    name: str
    url: str
    auth_type: str
    credentials: Optional[str] = None
    last_validated_at: Optional[datetime] = None
    default_windows_index: Optional[str] = None
    default_linux_index: Optional[str] = None
    default_cloud_index: Optional[str] = None
    log_marker_pattern: str = "purvex_*"

class SIEMConnectionCreate(SIEMConnectionBase):
    pass

class SIEMConnection(SIEMConnectionBase):
    id: int
    organization_id: Optional[int] = None
    status: Optional[str] = None
    credentials_present: bool = False

    model_config = ConfigDict(from_attributes=True)

class SIEMAlert(BaseModel):
    alert_id: Optional[str] = None
    rule_id: Optional[str] = None
    rule_name: Optional[str] = None
    severity: Optional[str] = None
    status: Optional[str] = None
    fired_at: Optional[datetime] = None
    last_seen_at: Optional[datetime] = None
    source: Optional[str] = None
    raw_event: Optional[str] = None
    evidence_url: Optional[str] = None

class SIEMEvent(BaseModel):
    event_id: Optional[str] = None
    event_time: Optional[datetime] = None
    severity: Optional[str] = None
    source: Optional[str] = None
    host: Optional[str] = None
    user: Optional[str] = None
    action: Optional[str] = None
    raw_event: Optional[str] = None
    evidence_url: Optional[str] = None

class SIEMEvidence(BaseModel):
    event_time: Optional[datetime] = None
    severity: Optional[str] = None
    host: Optional[str] = None
    user: Optional[str] = None
    dest: Optional[str] = None
    src: Optional[str] = None
    signature: Optional[str] = None
    sourcetype: Optional[str] = None
    index: Optional[str] = None

class SIEMEvidenceBundle(BaseModel):
    count: int
    items: List[SIEMEvidence]
    deep_link: Optional[str] = None

class SIEMRule(BaseModel):
    rule_id: Optional[str] = None
    name: Optional[str] = None
    enabled: Optional[bool] = None
    severity: Optional[str] = None
    schedule: Optional[str] = None
    last_run_at: Optional[datetime] = None
    query: Optional[str] = None
    evidence_url: Optional[str] = None

class SIEMHealth(BaseModel):
    status: str
    auth_status: Optional[str] = None
    ingestion_lag_seconds: Optional[int] = None
    last_event_at: Optional[datetime] = None
    last_alert_at: Optional[datetime] = None
    message: Optional[str] = None

class EnvironmentRunnerConfigBase(BaseModel):
    organization_id: Optional[int] = None
    environment_name: str
    runner_type: str = "SSH"
    hostname: Optional[str] = None
    port: int = 22
    username: Optional[str] = None
    auth_method: str = "key"
    key_path: Optional[str] = None
    allowed_test_types: str = '["Atomic only"]'
    max_concurrent_tests: int = 1
    heartbeat_interval_seconds: int = 5
    alert_offline_minutes: int = 5
    os: Optional[str] = None
    ip_address: Optional[str] = None
    agent_version: Optional[str] = None
    last_check_in: Optional[datetime] = None
    status: Optional[str] = None
    owner_name: Optional[str] = None
    owner_email: Optional[str] = None
    runner_token_last_rotated_at: Optional[datetime] = None
    runner_token_expires_at: Optional[datetime] = None

class EnvironmentRunnerHeartbeat(BaseModel):
    os: Optional[str] = None
    ip_address: Optional[str] = None
    agent_version: Optional[str] = None
    status: Optional[str] = None

class EnvironmentRunnerConfigCreate(EnvironmentRunnerConfigBase):
    pass

class EnvironmentRunnerConfig(EnvironmentRunnerConfigBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

class EnvironmentRunnerRegistrationResponse(EnvironmentRunnerConfig):
    runner_token: Optional[str] = None

class AgentCommand(BaseModel):
    id: int
    runner_id: int
    command_type: str
    status: str
    payload: Optional[str] = None
    message: Optional[str] = None
    created_at: Optional[datetime] = None
    acknowledged_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)

class AgentCommandAck(BaseModel):
    status: str
    message: Optional[str] = None

class TestingPolicyBase(BaseModel):
    organization_id: Optional[int] = None
    allowed_environments: str = '["lab", "dev"]'
    default_marker_prefix: str = "purvex_"
    include_env_timestamp_in_marker: bool = True
    tag_test_alerts: str = "Purvex_Test = true"
    notify_before_prod_tests: bool = False
    disallow_tests_during_business_hours: bool = False
    business_hours_start: str = "09:00"
    business_hours_end: str = "17:00"
    only_prod_during_maintenance_windows: bool = False
    # SIEM-style data retention for test runs and stored SIEM samples (in days).
    test_data_retention_days: int = 90
    retention_pass_days_lab: int = 7
    retention_fail_days_lab: int = 30
    retention_pass_days_dev: int = 30
    retention_fail_days_dev: int = 90
    retention_pass_days_prod: int = 90
    retention_fail_days_prod: int = 180

class TestingPolicyCreate(TestingPolicyBase):
    pass

class TestingPolicy(TestingPolicyBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

class DetectionScoringBase(BaseModel):
    organization_id: Optional[int] = None
    base_scoring_explanation: str = "PASS with logs → base 80, FAIL with logs → base 30, INCONCLUSIVE → base 50"
    pass_log_base_score: int = 80
    fail_log_base_score: int = 30
    inconclusive_base_score: int = 50
    recent_pass_fail_weight: int = 10
    false_positive_penalty: int = 10
    environment_penalty_discount: int = 0
    health_threshold_healthy: int = 80
    health_threshold_at_risk: int = 50
    health_threshold_critical: int = 20
    scoring_window_n_tests: int = 10

class DetectionScoringCreate(DetectionScoringBase):
    pass

class DetectionScoring(DetectionScoringBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

class AIAssistantSettingsBase(BaseModel):
    organization_id: Optional[int] = None
    provider: str = "OpenAI"
    model_name: str = "gpt-4o-mini"
    api_base_url: str = "https://api.openai.com/v1"
    api_key: Optional[str] = None
    analysis_mode: Optional[str] = "fast"
    generate_tuning_suggestions: bool = True
    explain_test_failures: bool = True
    automatically_modify_rules: bool = False
    strip_ips_hostnames: bool = True
    no_raw_logs_outside_env: bool = False
    audience_preference: str = "Analyst"

    model_config = ConfigDict(protected_namespaces=())

class AIAssistantSettingsCreate(AIAssistantSettingsBase):
    pass

class AIAssistantSettings(AIAssistantSettingsBase):
    id: int

    model_config = ConfigDict(from_attributes=True)


class AuditEvent(BaseModel):
    id: int
    user_id: Optional[int] = None
    user_email: Optional[str] = None
    action: str
    resource_type: Optional[str] = None
    resource_id: Optional[str] = None
    details: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SandboxEnvironmentBase(BaseModel):
    organization_id: Optional[int] = None
    external_id: Optional[str] = None
    display_name: str = "PurveX Lab"
    status: str = "provisioning"
    size: Optional[str] = "small"
    provider: Optional[str] = "purvex_cloud"
    extra_metadata: Optional[str] = None


class SandboxEnvironmentCreate(SandboxEnvironmentBase):
    pass


class SandboxEnvironment(SandboxEnvironmentBase):
    id: int
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class TestScheduleBase(BaseModel):
    detection_id: Optional[str] = None
    technique_id: Optional[str] = None
    environment: str = "lab"
    mode: str = "DETECTION_VALIDATION"
    schedule_type: str  # "once" | "interval" | "cron"
    run_at: Optional[datetime] = None
    interval_seconds: Optional[int] = None
    cron_expression: Optional[str] = None
    enabled: bool = True


class TestScheduleCreate(TestScheduleBase):
    pass


class TestSchedule(TestScheduleBase):
    id: int
    organization_id: Optional[int] = None
    created_by_user_id: Optional[int] = None
    created_at: datetime
    last_run_at: Optional[datetime] = None
    next_run_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)
